### PR TITLE
Add a copyright license (CC-BY-SA, though I'm happy to change it)

### PR DESCRIPTION
**Pull request by notriddle**
Technically :smile: I've violated copyright by duplicating your work without explicit permission, as have all the other contributors (I think it varies by jurisdiction whether the temporary copy produced by opening the web page needs a copyright license).

To relicense, we'll need permission from all contributors:
- [x] @luciotato
- [x] @wwwillchen
- [ ] @kuangchanglang
- [x] @abusque
- [x] @guywithnose
- [ ] James Andrews git@enigmanorth.com (ugh, no GitHub account)

### CODE REVIEW

**Comment by abusque** [comment]
You have my full permission if you want to go ahead with this change.

**Comment by guywithnose** [comment]
:+1:

**Comment by luciotato** [comment]
CC-BY-SA is ok... but... the use of the forbidden word!! :) ... 
I'll mark a demerit for you Sr...

**Comment by notriddle** [comment]
Um... did you get permission from the other three people?

**Comment by wwwillchen** [comment]
OK with me.

**Pull request merged**
